export class Bag{
    id?: number;
    subject: string;
    description: string;
    coverage: string;
    title: string;
    publisher: string;
    identifier: string;
    creator: string;
    language: string;
    contributor: string;
    type: string;
    date: string;
    relation: string;
    source: string;
    format: string;
    rights: string;
    payload_oxum: string;
    bagging_date: string;
    bag_size: string;
    bagscol: string;
    deleted_at: string;
    bag_id: number;
    url: string;
    extention: string;
    collection_id: number;
    organisation_id: number;
    name: string;
}